<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="..\..\stylecop.json" Link="stylecop.json" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="CsvHelper" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Redis.OM" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\NetCore.Donation.Domain\NetCore.Donation.Domain.csproj" />
	</ItemGroup>
</Project>
