<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="..\..\stylecop.json" Link="stylecop.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AWSSDK.S3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\NetCore.Donation.Domain\NetCore.Donation.Domain.csproj" />
	</ItemGroup>

</Project>
